services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_model:/root/.ollama # model persistence
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: |                    
      ollama pull llama3.2-vision 
      wait -n 

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3dgeoref_python
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./example_data_path:/data
    restart: "no"